dependencies:
  - python=3.7.3
  - mpi4py=3.0.3
  - c-compiler=1.3.0
  - cmake=3.21.3
  - qt=5.12.5 
  - pip
  - pip:
    - gym==0.15.4
    - procgen==0.9.2
    - tensorflow==1.15.0
    - pytest # for baselines
    - gym3==0.3.3
    - numpy==1.17.2
    - filelock==3.0.10
